### ISSUE TITLE
突然发现Leo-Jo的项目不见了

### ISSUE THREAD

**Issue by jidanyunmian** [SuLingGG/openwrt-scripts#2]
√就是这个↓
https://github.com/Leo-Jo/luci-app-koolproxyR
？？？

**Comment by SuLingGG** [comment]
> √就是这个↓
> https://github.com/Leo-Jo/luci-app-koolproxyR
> ？？？

luci-app-koolproxyR 现在好像已经不能用了，所以我也在脚本里移除了这个插件。
(顺便更新了下脚本)
